### ISSUE TITLE
Fail to install PyCLIPS via pip

### ISSUE THREAD

**Issue by Scrooge20291224** [almostearthling/pyclips#11]
Collecting pyclips
  Using cached https://files.pythonhosted.org/packages/36/2e/30b0ba0c724fb6dba9b96578c6cf0c77d7788c8986f13e67b8c88f5898a7/pyclips-1.0.7.343.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Scrooge\AppData\Local\Temp\pip-install-c9znf61n\pyclips\setup.py", line 29
        print "Module 'clips': Python to CLIPS interface"
                                                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Module 'clips': Python to CLIPS interface")?
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Scrooge\AppData\Local\Temp\pip-install-c9znf61n\pyclips\

**Comment by Scrooge20291224** [comment]
I think this is because I am using PY 3.6...maybe this issue can be defined as a py3 compatibility issue?

**Comment by almostearthling** [comment]
Of course, the symptom is exactly that: Py3 does not support the old print syntax, without parentheses and PyCLIPS was designed on Py2. I actually paused the development of PyCLIPS, and there are some forks around - I think, aimed also at porting PyCLIPS to Py3.

**Comment by virtiparekh** [comment]
I tried this with python 2.7 and also with python 3 . But I am getting same error can anyone please help with that
 
(kivy_venv) C:\Users\Virti Parekh>pip install pyclips
Collecting pyclips
  Using cached pyclips-1.0.7.343.tar.gz (1.1 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\virti parekh\kivy_venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Windows\\TEMP\\pip-install-obqd18bl\\pyclips\\setup.py'"'"'; __file__='"'"'C:\\Windows\\TEMP\\pip-install-obqd18bl\\pyclips\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Windows\TEMP\pip-pip-egg-info-wrj6qjag'
         cwd: C:\Windows\TEMP\pip-install-obqd18bl\pyclips\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Windows\TEMP\pip-install-obqd18bl\pyclips\setup.py", line 29
        print "Module 'clips': Python to CLIPS interface"
                                                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Module 'clips': Python to CLIPS interface")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by almostearthling** [comment]
Which one is the `pip` that is called? Try:

```
C:\Users\xxxxxxx>where pip
C:\[...]\Python-3.8\Scripts\pip.exe
C:\[...]\Python-2.7\Scripts\pip.exe
```

or

```
C:\Users\xxxxxxx>pip --version
pip 20.2 from C:\[...]\python-3.8\lib\site-packages\pip (python 3.8)
```

In case your setting is like this, try to use the full path to the Python 2.7 version to invoke `pip`.

**Comment by virtiparekh** [comment]
**I m using python 2.7 and pip version is 20.2 .**


> (pyclips) C:\Users\Virti Parekh>python --version
> Python 2.7.18 :: Anaconda, Inc.
> 
> (pyclips) C:\Users\Virti Parekh>pip --version
> pip 20.2.3 from c:\users\virti parekh\anaconda3\envs\pyclips\lib\site-packages\pip (python 2.7)

**While installing clips, I am still getting the following error.**

> (pyclips) C:\Users\Virti Parekh>pip install clips
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
> Collecting clips
>   Using cached clips-1.1.0.tar.gz (5.9 kB)
>     ERROR: Command errored out with exit status 1:
>      command: 'c:\users\virti parekh\anaconda3\envs\pyclips\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\windows\\temp\\pip-install-qehwad\\clips\\setup.py'"'"'; __file__='"'"'c:\\windows\\temp\\pip-install-qehwad\\clips\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\windows\temp\pip-pip-egg-info-7xukzx'
>          cwd: c:\windows\temp\pip-install-qehwad\clips\
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "c:\windows\temp\pip-install-qehwad\clips\setup.py", line 19, in <module>
>         except FileNotFoundError:
>     NameError: name 'FileNotFoundError' is not defined
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

 **Getting some error while installing pyclips in python 2.7** 

> (pyclips) C:\Users\Virti Parekh>pip install pyclips
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
> Collecting pyclips
>   Using cached pyclips-1.0.7.343.tar.gz (1.1 MB)
> Building wheels for collected packages: pyclips
>   Building wheel for pyclips (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: 'c:\users\virti parekh\anaconda3\envs\pyclips\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\windows\\temp\\pip-install-fg_efs\\pyclips\\setup.py'"'"'; __file__='"'"'c:\\windows\\temp\\pip-install-fg_efs\\pyclips\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'c:\windows\temp\pip-wheel-w0zznl'
>        cwd: c:\windows\temp\pip-install-fg_efs\pyclips\
> .................

**Thank You for your above advice . I am new to this. I also referred your repository of pyclips but I am not getting the clips 6.24 .tar file. But can you please suggest a solution for my issue.**
